name: Compatibility builds

on:
  workflow_dispatch:
  schedule:
    - cron: '5 6 * * *'

jobs:
  compatibility:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['2.6.14', '3.0.9', '3.1.2', '3.2.0-M1']

    name: Compatibility with Spring Boot ${{ matrix.version }}

    steps:

    - name: Check out sources
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'

    - name: Build
      run: ./mvnw -B verify -Dspring-boot.version=${{ matrix.version }} --file pom.xml
